# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bHwUtbvkRqnKAguuHkUXU2gW9Y_Y7OlY
"""

text = "hey, Sahil this side. This is my first text tokenization job in google collab!"

from nltk.tokenize import sent_tokenize

!pip install nltk

import nltk
nltk.download('punkt')

sent_tokenize_list = sent_tokenize(text)

print("\nSentence tokenizer:")
print(sent_tokenize_list)

# Create a new word tokenizer
from nltk.tokenize import word_tokenize
print ("\nWord tokenizer:")
print(word_tokenize(text))

